### ISSUE TITLE
A device which does not exist was specified. (os error 433)

### ISSUE THREAD

**Issue by YennIsHere** [jac3km4/redscript#102]
Firstly the reason I am posting this here it because it caused by redscript. My drives and OS arent the issue, being I've completely replaced my drives with brand new ones to test again. 

This error happens at random, sometimes it is at launch, sometimes its while playing, it happens at random points. Normally you could just say okay and restart the game, or verify the game cache, etc. With this error specifically it locks the steamapps folder and makes all games on the drive where cyberpunk is located completely inaccessible. It entirely locks the steam apps folder, so you cannot open it via file manager either as you get the same error, but through windows. 

![image](https://github.com/jac3km4/redscript/assets/146495530/cecae110-29de-4676-be77-6defebaf72b9)

Rebooting the pc makes the problem go away but the error will still occur again. Ive tried this with and without mods installed and get the same thing over and over again. Ive never had this problem before and after a week of trying to find a fix myself im making this post. Any help is appreciated.

**Comment by jac3km4** [comment]
@YennIsHere this is an error reported by the operating system, and simply forwarded to you by redscript, you should check your disk for errors, there are various tutorials on the internet that can help you do that, e.g. https://www.howtogeek.com/1033/how-to-use-chkdsk-on-windows/.

**Comment by YennIsHere** [comment]
Thats what i figured however I have run multiple disk checks, and ive also completely swapped disk drives and did a brand new install of windows.
