### ISSUE TITLE
Crash when unregistering callback Input/Key

### ISSUE THREAD

**Issue by manavortex** [jac3km4/redscript#104]
As I learned [yesterday](https://discord.com/channels/717692382849663036/804399334246187038/1223779634592612382), the game will crash when I try unregistering my Input/Key callback:

```swift

class ExampleEnv extends ScriptableEnv {
  private let m_callbackSystem: wref<CallbackSystem>;

  private func OnLoad() {
    this.m_callbackSystem = GameInstance.GetCallbackSystem();
    this.m_callbackSystem.RegisterCallback(n"Input/Key", this, n"OnKeyInput", true);
  }

  private cb func OnKeyInput(event: ref<KeyInputEvent>) {
    // this crashes
    this.m_callbackSystem.UnregisterCallback(n"Input/Key", this, n"OnKeyInput");    
  }
}

```

Is there a list of callback-able events anywhere that I haven't found? I'm especially interested in HUD initialized

**Comment by jac3km4** [comment]
maybe you're unregistering the callback multiple times?
either way, this is does not seem to be a compiler issue, so shouldn't be raised here

**Comment by manavortex** [comment]
Maybe too quickly. Sorry, didn't know this was the wrong place - where'd I go for it? :)

**Comment by jac3km4** [comment]
this particular class you're using is from Codeware (https://github.com/psiberx/cp2077-codeware), but it's probably best to ask on Discord, someone there might be familiar with this
