### ISSUE TITLE
Virustotal Threats on .26 compared to .24

### ISSUE THREAD

**Issue by NeatoPurrito** [jac3km4/redscript#106]
The newer Version of Redscript is showing some concerning warnings when scanned it also triggers antivirus services compared to before.

[https://www.virustotal.com/gui/file/be557f8577cff9c53778f1c507b34aed0fd8a05ac5625d68edaf10c96ec88e49](url)
Virustotal of .26 zip file

[https://www.virustotal.com/gui/file/45fae4d0f100a10b4a024629e891596cf39a7e741208e11aba2e34e098f3621e](url)
Virustotal of .24 zip file

**Comment by ondrovic** [comment]
your links were broken, but yes I agree will not even save locally in chrome

[0.5.26](https://www.virustotal.com/gui/file/be557f8577cff9c53778f1c507b34aed0fd8a05ac5625d68edaf10c96ec88e49)
[0.5.24](https://www.virustotal.com/gui/file/45fae4d0f100a10b4a024629e891596cf39a7e741208e11aba2e34e098f3621e)

Also trying to install via Vortex
![image](https://github.com/user-attachments/assets/4445ae8b-7c4e-43d3-a7c0-fedd81b4b1a1)

I downloaded the source and compiled my own version and got the following results

[Local Compiled 0.5.26](https://www.virustotal.com/gui/file/7bf3ad1f7e505278b3f6b558446f891b8066a19bbd850076a9feb1b877957f0f?nocache=1)

**Comment by jac3km4** [comment]
I've done a tiny re-release with no changes other than some minor dependency updates and this one doesn't get flagged: https://www.virustotal.com/gui/file/6e377a29069a6950a620618c4c643e623cb4ef4191404be7b76f4c164177fe57?nocache=1

I am not sure what caused the false positive, it might've been something with the Github CI machine that built the 0.5.26 release.

**Comment by ondrovic** [comment]
> I've done a tiny re-release with no changes other than some minor dependency updates and this one doesn't get flagged: https://www.virustotal.com/gui/file/6e377a29069a6950a620618c4c643e623cb4ef4191404be7b76f4c164177fe57?nocache=1
> 
> I am not sure what caused the false positive, it might've been something with the Github CI machine that built the 0.5.26 release.

Awesome thanks
