### ISSUE TITLE
redscript today.

### ISSUE THREAD

**Issue by darbok** [jac3km4/redscript#108]
I installed cyberpunk 2077 and liberty today, I installed redscript, virtual alterier and all required dependencies. I then I picked a shop to installed, installed it, had a redscript compilation error, then tried a different shop, same problem. I manually installed the mods, these are the newest versions.

Here is one log example:

[ERROR - Thu, 26 Dec 2024 22:20:49 -0500] [UNRESOLVED_TYPE] At G:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\busy_vampire_atlier_store\busy-vampire_boutique.reds:1:1:
@addMethod(gameuiInGameMenuGameController)
^^^
unresolved type 'VirtualShopRegistration'

[ERROR - Thu, 26 Dec 2024 22:20:49 -0500] [UNRESOLVED_METHOD] At G:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\busy_vampire_atlier_store\busy-vampire_boutique.reds:3:3:
  event.AddStore(
  ^^^
method 'AddStore' not found on 'IScriptable'

[ERROR - Thu, 26 Dec 2024 22:20:52 -0500] REDScript compilation has failed.
This error has been caused by mods listed below:
- busy_vampire_atlier_store

**Comment by jac3km4** [comment]
Hi,
It looks like you've installed a mod without a dependency it requires: https://www.nexusmods.com/cyberpunk2077/mods/2987. Install the dependency and it should work fine.
