### ISSUE TITLE
Please Setup NexusMods page for RedScript

### ISSUE THREAD

**Issue by SpudmanWP** [jac3km4/redscript#21]
As the title says, please set up a Mod page for RedScript on NexusMods.  It would only need to contain the release files and the scripts.ini within the appropriate folder structure.

The main purpose of this is for ModManager integration so that the user does not have to search for & apply changes manually.

If you do not want to then with your permission I would like to set it up, with full credit going to you & your team obviously.

**Comment by jac3km4** [comment]
I've had a look at that and I think Nexus doesn't like mods with `.exe` files (the compiler is an exe that is run by the game). I can create a mod page for it, but I can't upload the files because they get 'quarantined'. Not sure how to deal with that.

**Comment by SpudmanWP** [comment]
Is the exe packaged with folders in a zip/rar/7z archive?

Did you test it in ViruasTotal for a possible false positive?
I just ran it and it came back 100% clean.

I'll build a test Mod and follow up.

**Comment by SpudmanWP** [comment]
I just created a Mod page and got the same thing you did.
I think it's a catch-all for any EXE and just needs a Moderator's ok as I have seen many other "EXE" files on Nexus.

It's here:
https://www.nexusmods.com/cyberpunk2077/mods/1520

**Comment by jac3km4** [comment]
I've published the mod myself here:
https://www.nexusmods.com/cyberpunk2077/mods/1511/
I'm in touch with a moderator so I think I'll be able to get it approved.

**Comment by SpudmanWP** [comment]
Awesome, I'll remove mine since you have one up and running.

**Comment by SpudmanWP** [comment]
WOOT, you're live.  Now you just need to update it to 0.1.6 :)

![2021-02-07 12_09_56-Window](https://user-images.githubusercontent.com/4732338/107158215-7dd58980-693d-11eb-8005-f65d74e1a655.png)

I guess you can close this ticket now.

Good luck.

**Comment by jac3km4** [comment]
yay 🎊
