### ISSUE TITLE
User-defined classes referenced in other classes out of declaration order return an error

### ISSUE THREAD

**Issue by deadlymustard** [jac3km4/redscript#26]
I'm getting the following error when attempting to use my own classes. Note that this error does not occur during initial compilation (using redscript-vscode), only when running the game.
```
01:44:23 [ERROR] Unexpected error during compilation: PoolError("153166 is not a class")
Error: PoolError("153166 is not a class")
```

This error seems to be triggered when a class is used in another class before it has been declared. If I restructure the class to be declared before it's usage this error goes away. Additionally, if I add `1` in front of the file (so that the file is first in alphabetical order) it seems to get processed before any usage in another file and the error also goes away.

I would expect declaration/load order not to matter in this case.

Here's an example of something that's not working:
```swift
public class MyTestClass456 {
    public let myOtherTestClass: ref<MyTestClass123>;
}

public class MyTestClass123 {
    public let myTestVar: String;
}
```

However everything works fine if I restructure it like this:
```swift
public class MyTestClass123 {
    public let myTestVar: String;
}

public class MyTestClass456 {
    public let myOtherTestClass: ref<MyTestClass123>;
}
```

**Comment by jac3km4** [comment]
I think it's fixed with https://github.com/jac3km4/redscript/commit/e40f51ecfdde998f84a3db7b2846ac946ce5425c
