### ISSUE TITLE
Immutability/strange behavior in user-defined classes

### ISSUE THREAD

**Issue by deadlymustard** [jac3km4/redscript#27]
I'm noticing some odd behavior when I attempt to use my own custom classes in Redscript. It seems like either the class is not being initialized/instantiated properly or that the variables are immutable somehow.

Example:
```swift
class MyTestClass123 {
    public let myTestVar: String;
}
```
```swift
let testClass: ref<MyTestClass123>;
testClass = new MyTestClass123();
testClass.myTestVar = "Hello World!";
Log("My Test Var: " + testClass.myTestVar);
```
There are no compilation errors here, but I would expect to log `My Test Var: Hello World!` to the console. The above `Log` statement always returns comes back with a blank value for my the field in my class: 
`My Test Var: `

If I use a pre-existing class it returns as expected: 
```swift
public class GameAttachedEvent extends Event {
  public let isGameplayRelevant: Bool;
  public let displayName: String;
  public let contentScale: TweakDBID;
}
```
```swift
let evt: ref<GameAttachedEvent>;
evt = new GameAttachedEvent();
evt.displayName = "Hello World!";
Log("Display Name: " + evt.displayName);
```
Output:
`Display Name: Hello World!`

**Comment by jac3km4** [comment]
try running the same code with this https://github.com/jac3km4/redscript/commit/a9afb472c48c2818a18923547888901c365e60e6 patch

**Comment by deadlymustard** [comment]
@jac3km4 
Getting some compilation errors using the latest artifacts:

![image](https://user-images.githubusercontent.com/7128804/108118711-c04d4380-706c-11eb-8d31-c000a10d9cd3.png)

**Comment by deadlymustard** [comment]
Whoops, that actually may be related to the other issue. But I am using the latest artifact.

**Comment by jac3km4** [comment]
OK, can you give it another try from master?

**Comment by deadlymustard** [comment]
@jac3km4 Class ordering is working as expected, but still seeing issues with seemingly immutable classes. Another thing that may or may not help, it seems like methods that I call within my custom class aren't being called either.

```swift
public class LifePath {
    public let hasParents: Bool;
    public let gender: String;
    public let background: String;
    public let events: ref<LifePathEvents>;

    public func Initialize(gender: String) -> Void {
        Log("LifePath Initialized");
        this.gender = gender;
    }
}
```
```swift

let lifePath: ref<LifePath>;
lifePath = new LifePath();
lifePath.gender = "male";
Log("Lifepath Gender Before: " + lifePath.gender);

lifePath.Initialize("female");
Log("LifePath Gender After: " + lifePath.gender);
```

**Comment by jac3km4** [comment]
OK, I think this is fixed as well now. I've just run some tests in the game and everything seems to work fine on commit https://github.com/jac3km4/redscript/commit/5746cac2d2d79773e2c2aa6be646848be51fa911

**Comment by deadlymustard** [comment]
@jac3km4 Working great! Thanks as usual.
