### ISSUE TITLE
Member Undefined not found on EGameplayRole

### ISSUE THREAD

**Issue by djkovrik** [jac3km4/redscript#28]
Can't get access to Undefined member of EGameplayRole enum.
I guess it's also affects decompiler because there is a lot of missed references in dumped sources, like:
```
if Equals(this.GetCurrentGameplayRole(), EGameplayRole.) {
  // do something
};
```

**Comment by jac3km4** [comment]
I think there's a working workaround: use `IntEnum(0)`. The compiler should have syntax for these though so I consider this a bug.

**Comment by jac3km4** [comment]
addressed by emitting `IntEnum` in the decompiler for unnamed enum members 113798ff3db6c36ae850e303d029a16273a11b6c
