### ISSUE TITLE
Compiler source map fails if file doesn't end with newline

### ISSUE THREAD

**Issue by flibX0r** [jac3km4/redscript#31]
Ran across this edge case while I was digging through a monolithic `classes.redscript` and documenting things as comments in the new script file I was creating. I was using single line comments and hadn't put a newline at the end, it was commenting out the function annotation in the next file in the folder alphabetically.

Looks like it's because `Files.add(...)` in **compiler/src/source_map.rs** only splits on the newline character and just concatenates the source files together.

Easily avoided, but a possible issue. Perhaps fix with just forcing a newline at the end of every source file?

**Comment by flibX0r** [comment]
Also the compiler throws errors about the wrong file if there's a syntax error on the first line of any file that isn't the first one in a folder. Same fix would work.

**Comment by jac3km4** [comment]
I think this is fixed with https://github.com/jac3km4/redscript/commit/adbc68fbd4082ddfaad7bb20b76c90ac62ad70ec, feel free to give it a test

**Comment by flibX0r** [comment]
Yep, appears to be fixed. I can't replicate the error any more.
