### ISSUE TITLE
Allow addField to struct and add new struct

### ISSUE THREAD

**Issue by Nats-ji** [jac3km4/redscript#38]
addField to struct returns error: `Can't find class <struct_name>` 
trying to add new struct returns error: `expected one of "@"`

I want to add fields to `GameInstance` struct so I can pass values among classes.

**Comment by jac3km4** [comment]
Adding fields to structs is not supported right now, because it'd break existing struct constructors (they require N arguments where N is the number of fields in the struct).
I can't think of a good way to do it.
