### ISSUE TITLE
How to make old version scripts compatible for v0.3.0-RC1

### ISSUE THREAD

**Issue by DUTANGx** [jac3km4/redscript#48]
Thanks for your great work!
I'm trying to use some older-version scripts with redscript v0.3.0-RC1 but encountered errors such as:
 Member HasStatFlag not found on DefaultTransition
Is there any easy hack for older-version scripts being compatible with v0.3.0-RC1?
Many thanks

**Comment by jac3km4** [comment]
Hi,
There is no easy way to do this, you'll need to update the code to compile against the latest version of the game. Often this is pretty simple though - you can find the diff of the latest patch [here](https://codeberg.org/adamsmasher/cyberpunk/commit/926e1d689bb2494ffce597526bf7dc0702c7de17), you can use it to update the code.

**Comment by DUTANGx** [comment]
Thanks a lot, I will have a try :)
