### ISSUE TITLE
Corrupted scripts if parent class is declared after child

### ISSUE THREAD

**Issue by psiberx** [jac3km4/redscript#56]
The compiler produces a corrupted scripts file if the parent class is declared after the child class.

Test:
```swift
public class Child extends Base {}
public class Base {}
```

**Comment by jac3km4** [comment]
The code above works fine for me,
I've found a similar issue with my scripts but this snippet it not enough to reproduce an error

**Comment by jac3km4** [comment]
I've managed to reproduce this issue by compiling 2 mods + your snippet:
```
- @BaseLib
- InkPlayground
- snippet above
```
it looks like some combinations of mods triggered an edge case that wasn't covered by the existing sorting method,
I think this is fixed on master now with https://github.com/jac3km4/redscript/commit/85ebd54f3d13fbd4fb10fbec8b09b538a556e10d

**Comment by psiberx** [comment]
Yeah, this is fixed.
