### ISSUE TITLE
Lint hangs when @wrapMethod is used with an incorrect header

### ISSUE THREAD

**Issue by jackhumbert** [jac3km4/redscript#58]
This is similar to the block I had in my code, which caused `lint` to hang and grow in size until memory limits were reached:

```swift
@wrapMethod(hudCarController)
protected cb func OnRpmValueChanged()  -> Void {
  wrappedMethod();
}
```

Just for reference, this is the correct header that returns as normal;

```swift
@wrapMethod(hudCarController)
protected cb func OnRpmValueChanged(rpmValue: Float)  -> Void {
  wrappedMethod(rpmValue);
}
```

Thanks for all your work on this!

**Comment by jac3km4** [comment]
good catch,
this seems to be an issue with `cb` and `native` functions - the way they're matched (using function signatures) ignores the function parameter types which can lead to the compiler accepting invalid code like this

**Comment by jac3km4** [comment]
the lint doesn't hang anymore, it fails with an error (although not a very good one), but I think this can be closed
