### ISSUE TITLE
wrapMethod causes issues with callbacks

### ISSUE THREAD

**Issue by jac3km4** [jac3km4/redscript#63]
- `@wrapMethod` creates one method for every wrapper, but it looks like the game invokes every `cb` method on a class, so all of the wrappers get invoked
- `cb` methods should take exactly one argument and it's type should extend `Event`, this could be enforced by the compiler

**Comment by psiberx** [comment]
`cb` methods can have different signatures, `Event` based callback is just one variation that can cause issues with wrappers

**Comment by jac3km4** [comment]
the main issue has been adressed in a6a22cfd890ff1079b7bcd626cf6b211f93156a4
