### ISSUE TITLE
Allow importing native structs/defining new structs

### ISSUE THREAD

**Issue by deadlymustard** [jac3km4/redscript#70]
Currently we are unable to define custom/native structs, making a select few functions in the game's codebase unusable. 

One example is the `inkText` widget which should allow the definition of a word-wrap policy: 
`myInkTextWidget.SetWrappingInfo(new textWrappingInfo(true, 1000000.0, textWrappingPolicy.Default));`

Since the native struct `textWrappingInfo` is not exposed by default (and not able to be imported into Redscript currently) and we cannot define a custom struct we cannot actually pass in the required parameters. This makes defining custom widgets created in Redscript that also rely on text wrapping difficulty.

There may be other similar examples in the codebase as well.

**Comment by jac3km4** [comment]
I've added basic support [here](https://github.com/jac3km4/redscript/pull/71), feel free to test if you want

**Comment by deadlymustard** [comment]
Awesome, thank you. Will test this out soon!

**Comment by jac3km4** [comment]
it's been merged and released now,
create a new issue if you run into any problems
