### ISSUE TITLE
Nexus Version is (possibly) out of date

### ISSUE THREAD

**Issue by Krythulu** [jac3km4/redscript#72]
Simple issue, I don't think the Nexus version of this mod is broken. It crashes to desktop when using the Nexus version but the git hub version is fine

Not too important but still needs to be addressed

**Comment by jac3km4** [comment]
Nexus version is the same as the one in the latest release here, I've been hearing that the Nexus Cyberpunk plugin is currently broken and it affects all mods, not just redscript.
