### ISSUE TITLE
Cyberpunk doesn't launch if redscript is installed

### ISSUE THREAD

**Issue by Edvards55** [jac3km4/redscript#79]
the game will only launch if the files are verified after the mod has been removed I tested both redscript 0.5.8 and 0.5.9 the game version is 1.61
![image](https://user-images.githubusercontent.com/26838498/201476983-960cd533-cbb3-493f-93eb-ffdf7738cc3b.png)

**Comment by jac3km4** [comment]
This is not a redscript compiler issue. Likely one of your mods is broken, I recommend checking the community discord server if you need help to identify the individual mods causing your issues:
https://discord.gg/redmodding
