### ISSUE TITLE
[Issue] redscript doesn't seem to work with 1.61 DLSS3 patch

### ISSUE THREAD

**Issue by ghost** [jac3km4/redscript#86]
**[Issue] redscript doesn't seem to work with 1.61 DLSS3 patch**

Pretty much just the title.
[New patch dropped](https://www.cyberpunk.net/en/news/47434/dlss-3-reflex-pc-update), which seemingly broke redscript.

Game at least doesn't want to run, with anything related to redscript enabled.

I'm not smart enough for a PR, but would be nice if you had the time to take a look at it 👍 

Kind regards,
VP-EN

**Comment by jac3km4** [comment]
The patch doesn't affect redscript, make sure your other mods are up-to-date (red4ext, archivexl etc.)
