### ISSUE TITLE
Needs fix for 1.62-hotfix

### ISSUE THREAD

**Issue by gir489returns** [jac3km4/redscript#87]
Today's hotfix broke this. Causes this error when launching the game now.

![image](https://user-images.githubusercontent.com/100792176/233446452-96b82fcc-1030-485e-82a7-f1392e1a8f25.png)

There is nothing of value in the logs.

`[INFO - Thu, 20 Apr 2023 13:45:10 -0400] Using defaults for the script manifest (manifest not present)
[INFO - Thu, 20 Apr 2023 13:45:10 -0400] Compiling files: E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\ArchiveXL\ArchiveXL.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\CyberArms Collection Male Store-atelier-store.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\food-atelier\Bar-atelier-store.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\food-atelier\DrinkVendor-atelier-store.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\food-atelier\FoodVendor-atelier-store.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\infJump.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\legendary-weapons-mods-eshop\WeaponsMods-atelier-store.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\legendary-weapons-mods-eshop\WeaponsMuzzleScope-atelier-store.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\LegendaryWeapons-atelier-store.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\RecipeStore-atelier-store.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\TweakXL\TweakXL.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\AtelierTextButton.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\Browser.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\inkCharacterEvent.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\inkCharacterEventType.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\inkCustomController.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\inkFitToContentDirection.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\inkImage.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\inkScrollArea.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\inkWidget.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\inkWidgetHelper.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\TextInput\HubTextInput.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\TextInput\Parts\Caret.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\TextInput\Parts\Selection.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\TextInput\Parts\TextFlow.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\TextInput\Parts\TextMeasurer.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\TextInput\Parts\Viewport.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\codeware\TextInput\TextInput.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\Computer.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\ItemTooltips.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\atelier\WebPage.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\compat.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\config.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\constants.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\declarations.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\fields.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\helpers\ButtonHintsHelper.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\helpers\InputHelper.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\helpers\NotificationHelper.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\helpers\WidgetsHelper.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\items-preview\Backpack.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\items-preview\ItemPreview.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\managers\CurrentPlayerZoneManager.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\managers\ItemPreviewManager.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\managers\StoresManager.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\texts.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\utils.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\vendor-preview\ButtonHints.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\vendor-preview\FullscreenVendor.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\vendor-preview\FullscreenVendorHelpers.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\vendor-preview\FullscreenVendorVirtual.reds, E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\scripts\virtual-atelier\vendor-preview\GarmentItemPreview.reds
[INFO - Thu, 20 Apr 2023 13:45:10 -0400] Compilation complete
[INFO - Thu, 20 Apr 2023 13:45:10 -0400] Output successfully saved in E:\SteamLibrary\steamapps\common\Cyberpunk 2077\r6\cache
`

**Comment by jac3km4** [comment]
Today's update doesn't affect redscript, but a lot of other mods like cet/red4ext are affected and you will need to delete or update them.
