### ISSUE TITLE
CTD on v1.63

### ISSUE THREAD

**Issue by spacesynth** [jac3km4/redscript#95]
I am experiencing crashes to desktop on patch 1.63.

**Comment by jac3km4** [comment]
1.63 is a minor patch that doesn't affect redscript itself, you're likely experiencing an issue with some other mod, you should try following standard troubleshooting steps: https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-users/user-guide-troubleshooting/users-troubleshooting-after-a-game-update

**Comment by spacesynth** [comment]
I'm really sorry and could find the issue by scrubbing all mods and re-installing only the ones that were updated.

**Comment by Tyndareus** [comment]
You might want to reopen this since the hotfix that dropped after 1.63 has broken redscript
