### ISSUE TITLE
V0.5.15 vs v0.5.16 Atelier reds Issue

### ISSUE THREAD

**Issue by Kyberos** [jac3km4/redscript#96]
I noticed when i installed the unreleased v0.5.16 version the atelier reds files that all previous versions have been ok with were suddenly an issue.  It caused the all scripts to not load but game will launch anyway issue.  I thought i should say something.

**Comment by Kyberos** [comment]
If I'm reading this right it may be that the new version is just less forgiving and once Virtual Atelier is updated, which I don't have installed, these reds files for the stores will be fine... maybe.

[INFO - Thu, 28 Sep 2023 13:03:15 -0700] Using defaults for the script manifest (manifest not present)
[INFO - Thu, 28 Sep 2023 13:03:15 -0700] Bundle path provided: D:\Program Files (x86)\GOG Galaxy\Games\Cyberpunk 2077\r6\cache\final.redscripts
[INFO - Thu, 28 Sep 2023 13:03:15 -0700] Compiling files in D:\Program Files (x86)\GOG Galaxy\Games\Cyberpunk 2077\r6\scripts\:
appearanceChangeUnlocker\mirrorUnlocker.reds
ArchiveXL\ArchiveXL.reds
Codeware\Codeware.Global.reds
Codeware\Codeware.Localization.reds
Codeware\Codeware.reds
Codeware\Codeware.UI.reds
Codeware\Codeware.UI.TextInput.reds
DBRV n Co Virtual Atelier Store\DBRV&Co-Atelier-Store.reds
EquipmentEx\EquipmentEx.Global.reds
EquipmentEx\EquipmentEx.reds
TweakXL\TweakXL.reds
[WARN - Thu, 28 Sep 2023 13:03:15 -0700] At D:\Program Files (x86)\GOG Galaxy\Games\Cyberpunk 2077\r6\scripts\Codeware\Codeware.Global.reds:1860:1:
@addField(inkScrollArea)
^^^
field with this name is already defined in the class, this will have no effect

[ERROR - Thu, 28 Sep 2023 13:03:15 -0700] [UNRESOLVED_TYPE] At D:\Program Files (x86)\GOG Galaxy\Games\Cyberpunk 2077\r6\scripts\DBRV n Co Virtual Atelier Store\DBRV&Co-Atelier-Store.reds:1:1:
@addMethod(gameuiInGameMenuGameController)
^^^
unresolved type VirtualShopRegistration

[ERROR - Thu, 28 Sep 2023 13:03:15 -0700] [UNRESOLVED_METHOD] At D:\Program Files (x86)\GOG Galaxy\Games\Cyberpunk 2077\r6\scripts\DBRV n Co Virtual Atelier Store\DBRV&Co-Atelier-Store.reds:3:3:
  event.AddStore(
  ^^^
method AddStore not found on IScriptable

[ERROR - Thu, 28 Sep 2023 13:03:18 -0700] Compilation error: REDScript compilation failed. The game will start, but none of the scripts will take effect. This is caused by errors in:
- DBRV n Co Virtual Atelier Store
You can try updating or removing these scripts to resolve the issue. If you need more information, consult the logs.

**Comment by jac3km4** [comment]
There are no significant changes in 0.5.16 other than not requiring cybercmd. I suspect your redscript wasn't working properly in the first place because you didn't have cybercmd and the patch fixed it. The fix has exposed an underlying issue you had in your installation.

**Comment by Kyberos** [comment]
Yeah it's definitely my installation.  I have removed the atelier stores and it's fine now.  It's just they weren't a bother before the update.  I'll wait to see if an update to Virtual Atelier makes the reds files for the store fronts play nice again.

I was just trying to bring some attention to this issue in case there was something that maybe possibly got accidentally updated in the code rather than say nothing and expect the problem to fix itself.  If no one says anything and there is an actual problem then how will it ever get fixed?

Also, I'm seeing other people having issues with having atelier reds files still installed and a couple other mods also having issues.  Maybe those others are mod installation problems as well I don't know.
