### ISSUE TITLE
Crashing issues on latest release

### ISSUE THREAD

**Issue by firinggamers** [jac3km4/redscript#98]
the latest release of redscript is causing crashes in the game (im running on 2.01) have debugged with 

other files being on latest releases 
removing each and every single dependencies and testing them one by one turns out this one is causing issues.

**Comment by jac3km4** [comment]
It's most likely a script from some redscript-based mod causing your crash, try removing everything from `Cyberpunk 2077/r6/scripts` and your game will probably start fine.

**Comment by firinggamers** [comment]
> It's most likely a script from some redscript-based mod causing your crash, try removing everything from `Cyberpunk 2077/r6/scripts` and your game will probably start fine.

ive tried that  removing everything and works fine but when i use this script the game crashes but as u said let me try debugging with installing only redscript and nothing else and testing out if the game crashes then installing mods one by one and seeing which dependent mod is crashing it

**Comment by firinggamers** [comment]
got it its codeware
