### ISSUE TITLE
There was a mistake before entering the game

### ISSUE THREAD

**Issue by gaoningguo** [jac3km4/redscript#99]
`[ERROR - Wed, 25 Oct 2023 20:12:20 +0800] [SYM_REDEFINITION] At E:\DownLoad\ZhongZi\Cyberpunk 2077\Cyberpunk.2077.GOG.Rip-InsaneRamZes\Cyberpunk 2077\r6\scripts\player_underwear_removal_extended\native_definitions_incompatible_with_codeware.reds.reds:14:1:
public native struct gameFppRepDetachedObjectInfo {
symbol with this name is already defined
[ERROR - Wed, 25 Oct 2023 20:12:20 +0800] [SYM_REDEFINITION] At E:\DownLoad\ZhongZi\Cyberpunk 2077\Cyberpunk.2077.GOG.Rip-InsaneRamZes\Cyberpunk 2077\r6\scripts\player_underwear_removal_extended\native_definitions_incompatible_with_codeware.reds.reds:19:1:
public native struct gameTppRepAttachedObj^ectInfo {
symbol with this name is already defined
[ERROR - Wed, 25 Oct 2023 20:12:20 +0800] [SYM_REDEFINITION] At E:\DownLoad\ZhongZi\Cyberpunk 2077\Cyberpunk.2077.GOG.Rip-InsaneRamZes\Cyberpunk 2077\r6\scripts\player_underwear_removal_extended\native_definitions_incompatible_with_codeware.reds.reds:24:1:
public native class gameTPPRepresentationComponent extends IComponent {
symbol with this name is already defined
[ERROR - Wed, 25 Oct 2023 20:12:20 +0800] [SYM_REDEFINITION] At E:\DownLoad\ZhongZi\Cyberpunk 2077\Cyberpunk.2077.GOG.Rip-InsaneRamZes\Cyberpunk 2077\r6\scripts\player_underwear_removal_extended\native_definitions_incompatible_with_codeware.reds.reds:30:1:
public abstract native class gameuiICharacterCustomizationComponent extends IComponent {}
symbol with this name is already defined`
There was an error before entering the game, the following issues conflict with other pre-mods?  What about other mo bugs that depend on this mod?  Or is redscript itself wrong?

**Comment by flibdev** [comment]
Do you have Codeware installed along with "Player Underwear Removal Extended - Incompatible With Codeware" in your lovely pirate copy of the game?
